refactor: Doon't try executing waybar script if dependencies are not installed

diff --git a/scripts/waybar-with-autoreload b/scripts/waybar-with-autoreload
--- a/scripts/waybar-with-autoreload
+++ b/scripts/waybar-with-autoreload
@@ -2,6 +2,24 @@
 
 CONFIG_FILES="$HOME/.config/waybar/config $HOME/.config/waybar/style.css"
 
+declare -A NEEDED_BINS=(
+  'inotifywait',
+  'waybar'
+)
+
+die() {
+  echo $@ >&2
+  exit 1
+}
+
+for bin in $NEEDED_BINS; do
+  [[ ! -z `command -v $bin` ]] || die "Missing required PATH executable: $bin"
+done
+
+for conf in $CONFIG_FILES; do
+   [[  -f "$conf" ]] || die "Missing config file: $conf"
+done
+
 trap "killall waybar" EXIT
 
 while true; do
